version: '3'

services:
  backend:
    build:
      context: .
    command: uvicorn app.main:router --host 0.0.0.0 --port 8000
    ports:
      - "80:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - VIRTUAL_HOST=test.diego-luque.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=test.diego-luque.com
      
# networks:
#   default:
#     name: web_private_red_webapps
#     external: true